py$(PYV): remove tox env folder $(@D)/.tox/py$(PYV)
py$(PYV): commands[0]> python -m pytest tests
============================= test session starts ==============================
platform sunos5 -- Python $(PYTHON_VERSION).X -- $(@D)/.tox/py$(PYV)/bin/python
cachedir: .tox/py$(PYV)/.pytest_cache
rootdir: $(@D)
configfile: pytest.ini
collecting ... collected 38 items

tests/test_subtests.py::TestFixture::test_simple_terminal_normal[normal] PASSED
tests/test_subtests.py::TestFixture::test_simple_terminal_normal[xdist] PASSED
tests/test_subtests.py::TestFixture::test_simple_terminal_verbose[normal] PASSED
tests/test_subtests.py::TestFixture::test_simple_terminal_verbose[xdist] PASSED
tests/test_subtests.py::TestFixture::test_skip[normal] PASSED
tests/test_subtests.py::TestFixture::test_skip[xdist] PASSED
tests/test_subtests.py::TestFixture::test_xfail[normal] PASSED
tests/test_subtests.py::TestFixture::test_xfail[xdist] PASSED
tests/test_subtests.py::TestFixture::test_typing_exported[normal] PASSED
tests/test_subtests.py::TestFixture::test_typing_exported[xdist] PASSED
tests/test_subtests.py::TestSubTest::test_simple_terminal_normal[unittest] PASSED
tests/test_subtests.py::TestSubTest::test_simple_terminal_normal[pytest-normal] PASSED
tests/test_subtests.py::TestSubTest::test_simple_terminal_normal[pytest-xdist] PASSED
tests/test_subtests.py::TestSubTest::test_simple_terminal_verbose[unittest] PASSED
tests/test_subtests.py::TestSubTest::test_simple_terminal_verbose[pytest-normal] PASSED
tests/test_subtests.py::TestSubTest::test_simple_terminal_verbose[pytest-xdist] PASSED
tests/test_subtests.py::TestSubTest::test_skip[unittest] PASSED
tests/test_subtests.py::TestSubTest::test_skip[pytest-normal] XFAIL
tests/test_subtests.py::TestSubTest::test_skip[pytest-xdist] XFAIL (...)
tests/test_subtests.py::TestSubTest::test_xfail[unittest] XFAIL (Not...)
tests/test_subtests.py::TestSubTest::test_xfail[pytest-normal] XFAIL
tests/test_subtests.py::TestSubTest::test_xfail[pytest-xdist] XFAIL
tests/test_subtests.py::TestSubTest::test_skip_with_failure[unittest] PASSED
tests/test_subtests.py::TestSubTest::test_skip_with_failure[pytest-normal] PASSED
tests/test_subtests.py::TestSubTest::test_skip_with_failure[pytest-xdist] XFAIL
tests/test_subtests.py::TestSubTest::test_skip_with_failure_and_non_subskip[unittest] PASSED
tests/test_subtests.py::TestSubTest::test_skip_with_failure_and_non_subskip[pytest-normal] PASSED
tests/test_subtests.py::TestSubTest::test_skip_with_failure_and_non_subskip[pytest-xdist] XFAIL
tests/test_subtests.py::TestCapture::test_capturing PASSED
tests/test_subtests.py::TestCapture::test_no_capture PASSED
tests/test_subtests.py::TestCapture::test_capture_with_fixture[capsys] PASSED
tests/test_subtests.py::TestCapture::test_capture_with_fixture[capfd] PASSED
tests/test_subtests.py::TestLogging::test_capturing PASSED
tests/test_subtests.py::TestLogging::test_caplog PASSED
tests/test_subtests.py::TestLogging::test_no_logging PASSED
tests/test_subtests.py::TestDebugging::test_pdb_fixture PASSED
tests/test_subtests.py::TestDebugging::test_pdb_unittest PASSED
tests/test_subtests.py::test_exitfirst PASSED

=============================== warnings summary ===============================
tests/test_subtests.py:369
  $(@D)/tests/test_subtests.py:369: DeprecationWarning: invalid escape sequence \(
    "FAIL: test_foo \(__main__\.T\) \[custom message\] \(i=4\).*",

tests/test_subtests.py:370
  $(@D)/tests/test_subtests.py:370: DeprecationWarning: invalid escape sequence \(
    "FAIL: test_foo \(__main__\.T\) \[custom message\] \(i=9\).*",

tests/test_subtests.py:372
  $(@D)/tests/test_subtests.py:372: DeprecationWarning: invalid escape sequence \(
    "FAILED \(failures=6, skipped=4\)",

tests/test_subtests.py:378
  $(@D)/tests/test_subtests.py:378: DeprecationWarning: invalid escape sequence \(
    "FAIL: test_foo \(__main__\.T\.test_foo\) \[custom message\] \(i=4\).*",

tests/test_subtests.py:379
  $(@D)/tests/test_subtests.py:379: DeprecationWarning: invalid escape sequence \(
    "FAIL: test_foo \(__main__\.T\.test_foo\) \[custom message\] \(i=9\).*",

tests/test_subtests.py:381
  $(@D)/tests/test_subtests.py:381: DeprecationWarning: invalid escape sequence \(
    "FAILED \(failures=6, skipped=4\)",

tests/test_subtests.py:438
  $(@D)/tests/test_subtests.py:438: DeprecationWarning: invalid escape sequence \(
    "FAIL: test_foo \(__main__\.T\) \[custom message\] \(i=4\).*",

tests/test_subtests.py:439
  $(@D)/tests/test_subtests.py:439: DeprecationWarning: invalid escape sequence \(
    "FAIL: test_foo \(__main__\.T\) \[custom message\] \(i=9\).*",

tests/test_subtests.py:441
  $(@D)/tests/test_subtests.py:441: DeprecationWarning: invalid escape sequence \(
    "FAILED \(failures=6, skipped=5\)",

tests/test_subtests.py:447
  $(@D)/tests/test_subtests.py:447: DeprecationWarning: invalid escape sequence \(
    "FAIL: test_foo \(__main__\.T\.test_foo\) \[custom message\] \(i=4\).*",

tests/test_subtests.py:448
  $(@D)/tests/test_subtests.py:448: DeprecationWarning: invalid escape sequence \(
    "FAIL: test_foo \(__main__\.T\.test_foo\) \[custom message\] \(i=9\).*",

tests/test_subtests.py:450
  $(@D)/tests/test_subtests.py:450: DeprecationWarning: invalid escape sequence \(
    "FAILED \(failures=6, skipped=5\)",

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
======== 31 passed, 7 xfailed, 12 warnings ========
  py$(PYV): OK
  congratulations :)
